version: 2
jobs:
  build:
    docker:
      - image: cypress/base:18.16.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    parallelism: 2
    steps:
      # dependencies
      # clone @knapsack-pro/core project
      - run:
          name: Checkout code of @knapsack-pro/core
          command: cd ~ && (git clone -b $CIRCLE_BRANCH --single-branch https://github.com/KnapsackPro/knapsack-pro-core-js.git || git clone --single-branch https://github.com/KnapsackPro/knapsack-pro-core-js.git)

      - restore_cache:
          keys:
            - v1-knapsack-pro-core-{{ checksum "~/knapsack-pro-core-js/package.json" }}
            # fallback to the latest cache if no exact match is found
            - v1-knapsack-pro-core-

      - run: cd ~/knapsack-pro-core-js && npm install
      - run: cd ~/knapsack-pro-core-js && npm run build
      - run: cd ~/knapsack-pro-core-js && npm link

      - save_cache:
          name: Saving Cache of @knapsack-pro/core
          key: v1-knapsack-pro-core-{{ checksum "~/knapsack-pro-core-js/package.json" }}
          paths:
            - ~/knapsack-pro-core-js/node_modules

      # clone @knapsack-pro/cypress project
      - run:
          name: Checkout code of @knapsack-pro/cypress
          command: cd ~ && (git clone -b $CIRCLE_BRANCH --single-branch https://github.com/KnapsackPro/knapsack-pro-cypress.git || git clone --single-branch https://github.com/KnapsackPro/knapsack-pro-cypress.git)

      - restore_cache:
          keys:
            - v1-knapsack-pro-cypress-{{ checksum "~/knapsack-pro-cypress/package.json" }}
            # fallback to the latest cache if no exact match is found
            - v1-knapsack-pro-cypress-

      - run: cd ~/knapsack-pro-cypress && npm install
      - run: cd ~/knapsack-pro-cypress && npm link @knapsack-pro/core
      - run: cd ~/knapsack-pro-cypress && npm run build
      - run: cd ~/knapsack-pro-cypress && npm link

      - save_cache:
          name: Saving Cache of @knapsack-pro/cypress
          key: v1-knapsack-pro-cypress-{{ checksum "~/knapsack-pro-cypress/package.json" }}
          paths:
            - ~/knapsack-pro-cypress/node_modules

      # cypress-example-test-suite
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache

      - run:
          name: Run tests using @knapsack-pro/cypress installed from the NPM registry
          command: $(npm bin)/knapsack-pro-cypress

      # use a local version of @knapsack-pro/cypress
      - run: npm link @knapsack-pro/cypress

      - run:
          name: Run tests using the local version of @knapsack-pro/cypress
          # use a different CI build ID to run tests based on a new Knapsack Pro Queue
          command: KNAPSACK_PRO_CI_NODE_BUILD_ID=$CIRCLE_BUILD_NUM-v2 $(npm bin)/knapsack-pro-cypress
