version: 2
jobs:
  build:
    parallelism: 2
    docker:
      - image: cimg/node:16.15
        user: root
        environment:
          # In production you should use endpoint https://api.knapsackpro.com
          # which is default so it means you don't need to set KNAPSACK_PRO_ENDPOINT
          # Below endpoint is just for internal tests by KnapsackPro developers.
          KNAPSACK_PRO_ENDPOINT: https://api-staging.knapsackpro.com

    working_directory: ~/repo

    steps:
      # dependencies
      # clone @knapsack-pro/core project
      - run:
          name: Checkout code of @knapsack-pro/core
          command: cd ~ && (git clone -b $CIRCLE_BRANCH --single-branch https://github.com/KnapsackPro/knapsack-pro-core-js.git || git clone --single-branch https://github.com/KnapsackPro/knapsack-pro-core-js.git)

      - restore_cache:
          keys:
            - v1-knapsack-pro-core-{{ checksum "~/knapsack-pro-core-js/package.json" }}
            # fallback to the latest cache if no exact match is found
            - v1-knapsack-pro-core-

      - run: cd ~/knapsack-pro-core-js && npm install
      - run: cd ~/knapsack-pro-core-js && npm run build
      - run: cd ~/knapsack-pro-core-js && npm link

      - save_cache:
          name: Saving Cache of @knapsack-pro/core
          key: v1-knapsack-pro-core-{{ checksum "~/knapsack-pro-core-js/package.json" }}
          paths:
            - ~/knapsack-pro-core-js/node_modules

      # clone @knapsack-pro/jest project
      - run:
          name: Checkout code of @knapsack-pro/jest
          command: cd ~ && (git clone -b $CIRCLE_BRANCH --single-branch https://github.com/KnapsackPro/knapsack-pro-jest.git || git clone --single-branch https://github.com/KnapsackPro/knapsack-pro-jest.git)

      - restore_cache:
          keys:
            - v1-knapsack-pro-jest-{{ checksum "~/knapsack-pro-jest/package.json" }}
            # fallback to the latest cache if no exact match is found
            - v1-knapsack-pro-jest-

      - run: cd ~/knapsack-pro-jest && npm install
      - run: cd ~/knapsack-pro-jest && npm link @knapsack-pro/core
      - run: cd ~/knapsack-pro-jest && npm run build
      - run: cd ~/knapsack-pro-jest && npm link

      - save_cache:
          name: Saving Cache of @knapsack-pro/jest
          key: v1-knapsack-pro-jest-{{ checksum "~/knapsack-pro-jest/package.json" }}
          paths:
            - ~/knapsack-pro-jest/node_modules

      # jest-example-test-suite
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      # run tests!
      - run: $(npm bin)/knapsack-pro-jest
