# Javascript Node.js CircleCI 2.0 configuration file
# https://circleci.com/docs/2.0/language-javascript/

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/repo

    steps:
      # dependencies
      # @knapsack-pro/core project
      - run: cd ~ && (git clone -b $CIRCLE_BRANCH --single-branch https://github.com/KnapsackPro/knapsack-pro-core-js.git || git clone --single-branch https://github.com/KnapsackPro/knapsack-pro-core-js.git)

      - restore_cache:
          keys:
            - v1-knapsack-pro-core-{{ checksum "~/knapsack-pro-core-js/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-knapsack-pro-core-

      - run: cd ~/knapsack-pro-core-js && npm install
      - run: cd ~/knapsack-pro-core-js && npm run build
      - run: cd ~/knapsack-pro-core-js && sudo npm link

      - save_cache:
          paths:
            - ~/knapsack-pro-core-js/node_modules
          key: v1-knapsack-pro-core-{{ checksum "~/knapsack-pro-core-js/package.json" }}

      # @knapsack-pro/cypress project
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: npm link @knapsack-pro/core

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # build project
      - run: npm run build

      - run: npm run lint
